# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.3

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.3.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.3.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/juliorodrigues/Dropbox/Projetos Malucos/gb/gbemuc11"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/juliorodrigues/Dropbox/Projetos Malucos/gb/gbemuc11"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.3.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.3.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/juliorodrigues/Dropbox/Projetos Malucos/gb/gbemuc11/CMakeFiles" "/Users/juliorodrigues/Dropbox/Projetos Malucos/gb/gbemuc11/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/juliorodrigues/Dropbox/Projetos Malucos/gb/gbemuc11/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gbemuc11

# Build rule for target.
gbemuc11: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gbemuc11
.PHONY : gbemuc11

# fast build rule for target.
gbemuc11/fast:
	$(MAKE) -f CMakeFiles/gbemuc11.dir/build.make CMakeFiles/gbemuc11.dir/build
.PHONY : gbemuc11/fast

src/CPU.o: src/CPU.cpp.o

.PHONY : src/CPU.o

# target to build an object file
src/CPU.cpp.o:
	$(MAKE) -f CMakeFiles/gbemuc11.dir/build.make CMakeFiles/gbemuc11.dir/src/CPU.cpp.o
.PHONY : src/CPU.cpp.o

src/CPU.i: src/CPU.cpp.i

.PHONY : src/CPU.i

# target to preprocess a source file
src/CPU.cpp.i:
	$(MAKE) -f CMakeFiles/gbemuc11.dir/build.make CMakeFiles/gbemuc11.dir/src/CPU.cpp.i
.PHONY : src/CPU.cpp.i

src/CPU.s: src/CPU.cpp.s

.PHONY : src/CPU.s

# target to generate assembly for a file
src/CPU.cpp.s:
	$(MAKE) -f CMakeFiles/gbemuc11.dir/build.make CMakeFiles/gbemuc11.dir/src/CPU.cpp.s
.PHONY : src/CPU.cpp.s

src/GPU.o: src/GPU.cpp.o

.PHONY : src/GPU.o

# target to build an object file
src/GPU.cpp.o:
	$(MAKE) -f CMakeFiles/gbemuc11.dir/build.make CMakeFiles/gbemuc11.dir/src/GPU.cpp.o
.PHONY : src/GPU.cpp.o

src/GPU.i: src/GPU.cpp.i

.PHONY : src/GPU.i

# target to preprocess a source file
src/GPU.cpp.i:
	$(MAKE) -f CMakeFiles/gbemuc11.dir/build.make CMakeFiles/gbemuc11.dir/src/GPU.cpp.i
.PHONY : src/GPU.cpp.i

src/GPU.s: src/GPU.cpp.s

.PHONY : src/GPU.s

# target to generate assembly for a file
src/GPU.cpp.s:
	$(MAKE) -f CMakeFiles/gbemuc11.dir/build.make CMakeFiles/gbemuc11.dir/src/GPU.cpp.s
.PHONY : src/GPU.cpp.s

src/Main.o: src/Main.cpp.o

.PHONY : src/Main.o

# target to build an object file
src/Main.cpp.o:
	$(MAKE) -f CMakeFiles/gbemuc11.dir/build.make CMakeFiles/gbemuc11.dir/src/Main.cpp.o
.PHONY : src/Main.cpp.o

src/Main.i: src/Main.cpp.i

.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) -f CMakeFiles/gbemuc11.dir/build.make CMakeFiles/gbemuc11.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s

.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) -f CMakeFiles/gbemuc11.dir/build.make CMakeFiles/gbemuc11.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/RomPath.o: src/RomPath.cpp.o

.PHONY : src/RomPath.o

# target to build an object file
src/RomPath.cpp.o:
	$(MAKE) -f CMakeFiles/gbemuc11.dir/build.make CMakeFiles/gbemuc11.dir/src/RomPath.cpp.o
.PHONY : src/RomPath.cpp.o

src/RomPath.i: src/RomPath.cpp.i

.PHONY : src/RomPath.i

# target to preprocess a source file
src/RomPath.cpp.i:
	$(MAKE) -f CMakeFiles/gbemuc11.dir/build.make CMakeFiles/gbemuc11.dir/src/RomPath.cpp.i
.PHONY : src/RomPath.cpp.i

src/RomPath.s: src/RomPath.cpp.s

.PHONY : src/RomPath.s

# target to generate assembly for a file
src/RomPath.cpp.s:
	$(MAKE) -f CMakeFiles/gbemuc11.dir/build.make CMakeFiles/gbemuc11.dir/src/RomPath.cpp.s
.PHONY : src/RomPath.cpp.s

src/StringUtilscpp.o: src/StringUtilscpp.cpp.o

.PHONY : src/StringUtilscpp.o

# target to build an object file
src/StringUtilscpp.cpp.o:
	$(MAKE) -f CMakeFiles/gbemuc11.dir/build.make CMakeFiles/gbemuc11.dir/src/StringUtilscpp.cpp.o
.PHONY : src/StringUtilscpp.cpp.o

src/StringUtilscpp.i: src/StringUtilscpp.cpp.i

.PHONY : src/StringUtilscpp.i

# target to preprocess a source file
src/StringUtilscpp.cpp.i:
	$(MAKE) -f CMakeFiles/gbemuc11.dir/build.make CMakeFiles/gbemuc11.dir/src/StringUtilscpp.cpp.i
.PHONY : src/StringUtilscpp.cpp.i

src/StringUtilscpp.s: src/StringUtilscpp.cpp.s

.PHONY : src/StringUtilscpp.s

# target to generate assembly for a file
src/StringUtilscpp.cpp.s:
	$(MAKE) -f CMakeFiles/gbemuc11.dir/build.make CMakeFiles/gbemuc11.dir/src/StringUtilscpp.cpp.s
.PHONY : src/StringUtilscpp.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gbemuc11"
	@echo "... src/CPU.o"
	@echo "... src/CPU.i"
	@echo "... src/CPU.s"
	@echo "... src/GPU.o"
	@echo "... src/GPU.i"
	@echo "... src/GPU.s"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/RomPath.o"
	@echo "... src/RomPath.i"
	@echo "... src/RomPath.s"
	@echo "... src/StringUtilscpp.o"
	@echo "... src/StringUtilscpp.i"
	@echo "... src/StringUtilscpp.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

